#!/usr/bin/env python3
"""
Comprehensive test suite for VBS payload syntax validation
Verifies all payloads generate valid syntax with no undefined functions
"""

import unittest
from vbs_syntax_validator import VBSSyntaxValidator, validate_vbs_payload, SyntaxError
from vbs_encoder import VBSEncoder, generate_clean_vbs_payload
from vbs_advanced_obfuscation import AdvancedVBSObfuscation, create_stealthy_payload
from payload_generator import PayloadGenerator


class TestVBSSyntaxValidator(unittest.TestCase):
    """Test the VBS syntax validator itself"""

    def setUp(self):
        self.validator = VBSSyntaxValidator()

    def test_valid_simple_code(self):
        """Test validation of simple valid VBS code"""
        code = """
Dim shell
Set shell = CreateObject("WScript.Shell")
shell.Run "cmd /c test", 0, False
"""
        is_valid, errors = self.validator.validate(code)
        self.assertTrue(is_valid, f"Should be valid. Errors: {errors}")

    def test_undefined_function_detection(self):
        """Test detection of undefined functions"""
        code = """
Dim result
result = UndefinedFunction("test")
"""
        is_valid, errors = self.validator.validate(code)
        self.assertFalse(is_valid, "Should detect undefined function")
        self.assertTrue(any(e.error_type == "UNDEFINED_FUNCTION" for e in errors))

    def test_undefined_variable_in_context(self):
        """Test that declared variables are recognized"""
        code = """
Dim myVar
myVar = "test"
"""
        is_valid, errors = self.validator.validate(code)
        self.assertTrue(is_valid, f"Should recognize declared variables. Errors: {errors}")

    def test_mismatched_if_end(self):
        """Test detection of mismatched If/End If"""
        code = """
If True Then
    Dim x
    x = 1
End If
End If
"""
        is_valid, errors = self.validator.validate(code)
        self.assertFalse(is_valid, "Should detect mismatched End If")

    def test_unclosed_function(self):
        """Test detection of unclosed Function block"""
        code = """
Function MyFunc()
    Dim x
    x = 1
"""
        is_valid, errors = self.validator.validate(code)
        self.assertFalse(is_valid, "Should detect unclosed function")
        self.assertTrue(any(e.error_type == "UNCLOSED_BLOCK" for e in errors))

    def test_for_loop_balanced(self):
        """Test balanced For/Next loops"""
        code = """
Dim i
For i = 1 To 10
    Dim x
    x = i
Next
"""
        is_valid, errors = self.validator.validate(code)
        self.assertTrue(is_valid, f"Should have balanced For/Next. Errors: {errors}")

    def test_builtin_functions_allowed(self):
        """Test that built-in functions are recognized"""
        code = """
Dim s
s = LCase("TEST")
s = UCase(s)
s = Len(s)
s = Mid(s, 1, 1)
"""
        is_valid, errors = self.validator.validate(code)
        self.assertTrue(is_valid, f"Should allow built-in functions. Errors: {errors}")


class TestEncoderVBSSyntax(unittest.TestCase):
    """Test VBS syntax generated by VBSEncoder"""

    def setUp(self):
        self.encoder = VBSEncoder()
        self.validator = VBSSyntaxValidator()

    def test_base64_decoder_syntax(self):
        """Test base64 decoder generates valid VBS syntax"""
        vbs_code = self.encoder.create_base64_decoder_vbs("test payload")
        is_valid, errors = self.validator.validate(vbs_code)
        self.assertTrue(is_valid, f"Base64 decoder should be valid VBS. Errors:\n{self.validator.format_errors()}")

    def test_hex_decoder_syntax(self):
        """Test hex decoder generates valid VBS syntax"""
        vbs_code, _ = self.encoder.create_hex_decoder_vbs("test payload")
        is_valid, errors = self.validator.validate(vbs_code)
        self.assertTrue(is_valid, f"Hex decoder should be valid VBS. Errors:\n{self.validator.format_errors()}")

    def test_array_concatenation_decoder_syntax(self):
        """Test array concatenation decoder generates valid VBS"""
        vbs_code, _ = self.encoder.create_array_concatenation_decoder("test payload string")
        is_valid, errors = self.validator.validate(vbs_code)
        self.assertTrue(is_valid, f"Array decoder should be valid VBS. Errors:\n{self.validator.format_errors()}")

    def test_wscript_hidden_execution_syntax(self):
        """Test WScript hidden execution generates valid VBS"""
        vbs_code = self.encoder.create_wscript_hidden_execution("cmd /c test")
        is_valid, errors = self.validator.validate(vbs_code)
        self.assertTrue(is_valid, f"WScript execution should be valid VBS. Errors:\n{self.validator.format_errors()}")

    def test_polymorphic_wrapper_syntax(self):
        """Test polymorphic wrapper generates valid VBS"""
        code = "Dim x\nx = 1"
        wrapped = self.encoder.create_polymorphic_wrapper(code)
        is_valid, errors = self.validator.validate(wrapped)
        self.assertTrue(is_valid, f"Polymorphic wrapper should be valid VBS. Errors:\n{self.validator.format_errors()}")

    def test_full_obfuscated_base64_syntax(self):
        """Test full obfuscated base64 payload"""
        payload = self.encoder.create_full_obfuscated_payload("cmd /c test", "base64")
        is_valid, errors = self.validator.validate(payload)
        self.assertTrue(is_valid, f"Full obfuscated base64 should be valid. Errors:\n{self.validator.format_errors()}")

    def test_full_obfuscated_hex_syntax(self):
        """Test full obfuscated hex payload"""
        payload = self.encoder.create_full_obfuscated_payload("cmd /c test", "hex")
        is_valid, errors = self.validator.validate(payload)
        self.assertTrue(is_valid, f"Full obfuscated hex should be valid. Errors:\n{self.validator.format_errors()}")

    def test_full_obfuscated_array_syntax(self):
        """Test full obfuscated array payload"""
        payload = self.encoder.create_full_obfuscated_payload("cmd /c test", "array")
        is_valid, errors = self.validator.validate(payload)
        self.assertTrue(is_valid, f"Full obfuscated array should be valid. Errors:\n{self.validator.format_errors()}")

    def test_runtime_decoded_base64_syntax(self):
        """Test runtime decoded base64 payload"""
        payload = self.encoder.create_runtime_decoded_payload("cmd /c test", "base64")
        is_valid, errors = self.validator.validate(payload)
        self.assertTrue(is_valid, f"Runtime decoded base64 should be valid. Errors:\n{self.validator.format_errors()}")

    def test_runtime_decoded_hex_syntax(self):
        """Test runtime decoded hex payload"""
        payload = self.encoder.create_runtime_decoded_payload("cmd /c test", "hex")
        is_valid, errors = self.validator.validate(payload)
        self.assertTrue(is_valid, f"Runtime decoded hex should be valid. Errors:\n{self.validator.format_errors()}")


class TestAdvancedObfuscationVBSSyntax(unittest.TestCase):
    """Test VBS syntax from advanced obfuscation techniques"""

    def setUp(self):
        self.obf = AdvancedVBSObfuscation()
        self.validator = VBSSyntaxValidator()

    def test_environment_variable_decoder_syntax(self):
        """Test environment variable decoder syntax"""
        vbs_code = self.obf.create_environment_variable_decoder("test payload")
        is_valid, errors = self.validator.validate(vbs_code)
        self.assertTrue(is_valid, f"Environment variable decoder should be valid. Errors:\n{self.validator.format_errors()}")

    def test_wmi_execution_syntax(self):
        """Test WMI execution wrapper syntax"""
        vbs_code = self.obf.create_wmi_execution_wrapper("cmd /c test")
        is_valid, errors = self.validator.validate(vbs_code)
        self.assertTrue(is_valid, f"WMI execution should be valid. Errors:\n{self.validator.format_errors()}")

    def test_registry_stored_payload_syntax(self):
        """Test registry-stored payload syntax"""
        vbs_code = self.obf.create_registry_stored_payload("cmd /c test")
        is_valid, errors = self.validator.validate(vbs_code)
        self.assertTrue(is_valid, f"Registry payload should be valid. Errors:\n{self.validator.format_errors()}")

    def test_scheduled_task_injection_syntax(self):
        """Test scheduled task injection syntax"""
        vbs_code = self.obf.create_scheduled_task_injection("cmd /c test")
        is_valid, errors = self.validator.validate(vbs_code)
        self.assertTrue(is_valid, f"Scheduled task injection should be valid. Errors:\n{self.validator.format_errors()}")

    def test_com_object_obfuscation_syntax(self):
        """Test COM object obfuscation syntax"""
        vbs_code = self.obf.create_com_object_obfuscation("cmd /c test")
        is_valid, errors = self.validator.validate(vbs_code)
        self.assertTrue(is_valid, f"COM object obfuscation should be valid. Errors:\n{self.validator.format_errors()}")

    def test_obfuscated_function_calls_syntax(self):
        """Test obfuscated function calls syntax"""
        vbs_code = self.obf.create_obfuscated_function_calls("cmd /c test")
        is_valid, errors = self.validator.validate(vbs_code)
        self.assertTrue(is_valid, f"Obfuscated calls should be valid. Errors:\n{self.validator.format_errors()}")

    def test_filewriter_injection_syntax(self):
        """Test file writer injection syntax"""
        vbs_code = self.obf.create_filewriter_injection("cmd /c test")
        is_valid, errors = self.validator.validate(vbs_code)
        self.assertTrue(is_valid, f"File writer injection should be valid. Errors:\n{self.validator.format_errors()}")

    def test_multi_encoding_chain_syntax(self):
        """Test multi-encoding chain syntax"""
        vbs_code = self.obf.create_multi_encoding_chain("test payload")
        is_valid, errors = self.validator.validate(vbs_code)
        self.assertTrue(is_valid, f"Multi-encoding chain should be valid. Errors:\n{self.validator.format_errors()}")

    def test_chr_array_obfuscation_syntax(self):
        """Test Chr array obfuscation syntax"""
        code, var_name = self.obf.obfuscate_string_via_chr_array("test")
        # This returns just the expression, wrap in valid VBS
        full_code = f"Dim {var_name}\n{var_name} = {code}"
        is_valid, errors = self.validator.validate(full_code)
        self.assertTrue(is_valid, f"Chr array obfuscation should be valid. Errors:\n{self.validator.format_errors()}")


class TestPayloadGeneratorVBSSyntax(unittest.TestCase):
    """Test all payloads from PayloadGenerator"""

    def setUp(self):
        self.gen = PayloadGenerator()
        self.validator = VBSSyntaxValidator()
        self.test_command = "cmd /c echo test"

    def test_basic_technique_syntax(self):
        """Test basic technique generates valid syntax"""
        payload = self.gen.generate(self.test_command, technique="basic")
        is_valid, errors = self.validator.validate(payload)
        self.assertTrue(is_valid, f"Basic technique should generate valid VBS. Errors:\n{self.validator.format_errors()}")

    def test_base64_technique_syntax(self):
        """Test base64 technique generates valid syntax"""
        payload = self.gen.generate(self.test_command, technique="base64")
        is_valid, errors = self.validator.validate(payload)
        self.assertTrue(is_valid, f"Base64 technique should generate valid VBS. Errors:\n{self.validator.format_errors()}")

    def test_hex_technique_syntax(self):
        """Test hex technique generates valid syntax"""
        payload = self.gen.generate(self.test_command, technique="hex")
        is_valid, errors = self.validator.validate(payload)
        self.assertTrue(is_valid, f"Hex technique should generate valid VBS. Errors:\n{self.validator.format_errors()}")

    def test_array_technique_syntax(self):
        """Test array technique generates valid syntax"""
        payload = self.gen.generate(self.test_command, technique="array")
        is_valid, errors = self.validator.validate(payload)
        self.assertTrue(is_valid, f"Array technique should generate valid VBS. Errors:\n{self.validator.format_errors()}")

    def test_wmi_technique_syntax(self):
        """Test WMI technique generates valid syntax"""
        payload = self.gen.generate(self.test_command, technique="wmi")
        is_valid, errors = self.validator.validate(payload)
        self.assertTrue(is_valid, f"WMI technique should generate valid VBS. Errors:\n{self.validator.format_errors()}")

    def test_registry_technique_syntax(self):
        """Test registry technique generates valid syntax"""
        payload = self.gen.generate(self.test_command, technique="registry")
        is_valid, errors = self.validator.validate(payload)
        self.assertTrue(is_valid, f"Registry technique should generate valid VBS. Errors:\n{self.validator.format_errors()}")

    def test_env_technique_syntax(self):
        """Test env technique generates valid syntax"""
        payload = self.gen.generate(self.test_command, technique="env")
        is_valid, errors = self.validator.validate(payload)
        self.assertTrue(is_valid, f"Env technique should generate valid VBS. Errors:\n{self.validator.format_errors()}")

    def test_com_technique_syntax(self):
        """Test COM technique generates valid syntax"""
        payload = self.gen.generate(self.test_command, technique="com")
        is_valid, errors = self.validator.validate(payload)
        self.assertTrue(is_valid, f"COM technique should generate valid VBS. Errors:\n{self.validator.format_errors()}")

    def test_obfuscated_calls_technique_syntax(self):
        """Test obfuscated_calls technique generates valid syntax"""
        payload = self.gen.generate(self.test_command, technique="obfuscated_calls")
        is_valid, errors = self.validator.validate(payload)
        self.assertTrue(is_valid, f"Obfuscated calls technique should generate valid VBS. Errors:\n{self.validator.format_errors()}")

    def test_filewriter_technique_syntax(self):
        """Test filewriter technique generates valid syntax"""
        payload = self.gen.generate(self.test_command, technique="filewriter")
        is_valid, errors = self.validator.validate(payload)
        self.assertTrue(is_valid, f"Filewriter technique should generate valid VBS. Errors:\n{self.validator.format_errors()}")

    def test_multi_encoding_technique_syntax(self):
        """Test multi_encoding technique generates valid syntax"""
        payload = self.gen.generate(self.test_command, technique="multi_encoding")
        is_valid, errors = self.validator.validate(payload)
        self.assertTrue(is_valid, f"Multi-encoding technique should generate valid VBS. Errors:\n{self.validator.format_errors()}")

    def test_hidden_execution_technique_syntax(self):
        """Test hidden_execution technique generates valid syntax"""
        payload = self.gen.generate(self.test_command, technique="hidden_execution")
        is_valid, errors = self.validator.validate(payload)
        self.assertTrue(is_valid, f"Hidden execution technique should generate valid VBS. Errors:\n{self.validator.format_errors()}")

    def test_all_obfuscation_levels(self):
        """Test all obfuscation levels generate valid syntax"""
        for level in ["low", "medium", "high"]:
            payload = self.gen.generate(self.test_command, technique="base64", obfuscation_level=level)
            is_valid, errors = self.validator.validate(payload)
            self.assertTrue(is_valid, f"Obfuscation level {level} should be valid. Errors:\n{self.validator.format_errors()}")


class TestCleanVBSPayloadSyntax(unittest.TestCase):
    """Test clean VBS payload generation syntax"""

    def setUp(self):
        self.validator = VBSSyntaxValidator()

    def test_low_obfuscation_syntax(self):
        """Test low obfuscation generates valid syntax"""
        payload = generate_clean_vbs_payload("cmd /c test", "low")
        is_valid, errors = self.validator.validate(payload)
        self.assertTrue(is_valid, f"Low obfuscation should be valid. Errors:\n{self.validator.format_errors()}")

    def test_medium_obfuscation_syntax(self):
        """Test medium obfuscation generates valid syntax"""
        payload = generate_clean_vbs_payload("cmd /c test", "medium")
        is_valid, errors = self.validator.validate(payload)
        self.assertTrue(is_valid, f"Medium obfuscation should be valid. Errors:\n{self.validator.format_errors()}")

    def test_high_obfuscation_syntax(self):
        """Test high obfuscation generates valid syntax"""
        payload = generate_clean_vbs_payload("cmd /c test", "high")
        is_valid, errors = self.validator.validate(payload)
        self.assertTrue(is_valid, f"High obfuscation should be valid. Errors:\n{self.validator.format_errors()}")


class TestStealthyPayloadSyntax(unittest.TestCase):
    """Test stealthy payload generation syntax"""

    def setUp(self):
        self.validator = VBSSyntaxValidator()
        self.test_command = "cmd /c test"

    def test_wmi_technique_syntax(self):
        """Test WMI stealthy technique"""
        payload = create_stealthy_payload(self.test_command, "wmi")
        is_valid, errors = self.validator.validate(payload)
        self.assertTrue(is_valid, f"WMI stealthy should be valid. Errors:\n{self.validator.format_errors()}")

    def test_registry_technique_syntax(self):
        """Test registry stealthy technique"""
        payload = create_stealthy_payload(self.test_command, "registry")
        is_valid, errors = self.validator.validate(payload)
        self.assertTrue(is_valid, f"Registry stealthy should be valid. Errors:\n{self.validator.format_errors()}")

    def test_env_technique_syntax(self):
        """Test environment variable stealthy technique"""
        payload = create_stealthy_payload(self.test_command, "env")
        is_valid, errors = self.validator.validate(payload)
        self.assertTrue(is_valid, f"Env stealthy should be valid. Errors:\n{self.validator.format_errors()}")

    def test_com_technique_syntax(self):
        """Test COM stealthy technique"""
        payload = create_stealthy_payload(self.test_command, "com")
        is_valid, errors = self.validator.validate(payload)
        self.assertTrue(is_valid, f"COM stealthy should be valid. Errors:\n{self.validator.format_errors()}")

    def test_multi_technique_syntax(self):
        """Test multi-encoding stealthy technique"""
        payload = create_stealthy_payload(self.test_command, "multi")
        is_valid, errors = self.validator.validate(payload)
        self.assertTrue(is_valid, f"Multi stealthy should be valid. Errors:\n{self.validator.format_errors()}")

    def test_obfuscated_calls_technique_syntax(self):
        """Test obfuscated calls stealthy technique"""
        payload = create_stealthy_payload(self.test_command, "obfuscated_calls")
        is_valid, errors = self.validator.validate(payload)
        self.assertTrue(is_valid, f"Obfuscated calls stealthy should be valid. Errors:\n{self.validator.format_errors()}")

    def test_filewriter_technique_syntax(self):
        """Test filewriter stealthy technique"""
        payload = create_stealthy_payload(self.test_command, "filewriter")
        is_valid, errors = self.validator.validate(payload)
        self.assertTrue(is_valid, f"Filewriter stealthy should be valid. Errors:\n{self.validator.format_errors()}")


class TestNoUndefinedFunctions(unittest.TestCase):
    """Verify all payloads have no undefined function calls"""

    def setUp(self):
        self.validator = VBSSyntaxValidator()
        self.gen = PayloadGenerator()
        self.test_command = "cmd /c echo test"

    def _check_no_undefined_functions(self, payload: str, test_name: str):
        """Helper to check payload has no undefined functions"""
        is_valid, errors = self.validator.validate(payload)
        undefined_errors = [e for e in errors if e.error_type == "UNDEFINED_FUNCTION"]
        self.assertEqual(
            len(undefined_errors), 0,
            f"{test_name}: Found undefined functions: "
            f"{[e.message for e in undefined_errors]}\n\nPayload:\n{payload}"
        )

    def test_all_techniques_no_undefined_functions(self):
        """Test all techniques have no undefined functions"""
        for technique in self.gen.list_techniques():
            payload = self.gen.generate(self.test_command, technique=technique)
            self._check_no_undefined_functions(payload, f"Technique: {technique}")


if __name__ == "__main__":
    unittest.main(verbosity=2)
